[package]
name = "ai_cessible_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.6"
async-graphql = "6.0"
async-graphql-axum = "6.0"
tower-http = { version = "0.4", features = ["fs"] }
