openapi: 3.0.3
info:
  title: AI-cessible Server API
  version: 1.0.0
paths:
  /graphql:
    post:
      summary: Execute GraphQL operations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: GraphQL response
          content:
            application/json:
              schema:
                type: object
  /bot/graphql:
    post:
      summary: Execute bot-optimized GraphQL operations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: GraphQL response for bots
          content:
            application/json:
              schema:
                type: object
  /bot/behaviorMetrics:
    post:
      summary: Submit client-side behavior metrics
      requestBody:
        required: true
        content:
          application/json:
          schema:
            type: object
  /bot/intent:
    post:
      summary: Submit bot intent information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Intent accepted
          content:
            application/json:
              schema:
                type: object
    get:
      summary: Retrieve stored bot intents
      responses:
        '200':
          description: List of intents
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
